services:
  app:                        # The name of the service, can be anything
    image: todo-backend-app-1 # Declares which image to use
    build: .                  # Declares where to build if image is not found
    ports:                    # Declares the ports to publish
      - 3001:3000